### ISSUE TITLE
Consider using a state machine

### ISSUE THREAD

**Issue by ethers** [boardroom-project/boardroom-contracts#1]
some example contracts: http://www.arijuels.com/wp-content/uploads/2016/06/Setting-Standards-for-Altering-and-Undoing-Smart-Contracts.docx

**Comment by SilentCicero** [comment]
@ethers can you provide some basic concept examples, even if you have time, a bit of code?

**Comment by ethers** [comment]
the docx has example code.  Another public example is: http://solidity.readthedocs.io/en/latest/common-patterns.html#state-machine

**Comment by SilentCicero** [comment]
@ethers boardroom is relatively stateless, a state machine would be used in the Rules contract if anything, I can provide examples.
