### ISSUE TITLE
make project solc v0.4.2 compliant

### ISSUE THREAD

**Issue by gleim** [boardroom-project/boardroom-contracts#9]
upgrade contracts and dapple facilities to support solc 0.4.2

**Comment by SilentCicero** [comment]
I'll look into it, a few dapple test features will need to be reviewed first.

**Comment by SilentCicero** [comment]
added in latest commit https://github.com/boardroom-project/boardroom-contracts/commit/c0218b319fa2bb3a65d074d7b08bde53cc187a39
